### ISSUE TITLE
`load_schemata` refers to schemata in the plural (e.g. `'datasets'`) but `Config` refers to schemata in the singular (e.g. `DATASET_SCHEMA_URL`)

### ISSUE THREAD

**Issue by edwardleardi** [CODAIT/pardata#97]
I can see  the difference between a *dataset* schema (the `SchemaDict` the `Dataset` class requires) and the *datasets* schema (the global schema for all datasets) being confusing for beginner users. We should at minimum make sure all references to the latter are in the plural (e.g. `DATASETS_SCHEMA_URL` in place of `DATASET_SCHEMA_URL`).

**Comment by edwardleardi** [comment]
Also classes `DatasetSchema`, `FormatSchema`, and `LicenseSchema` are in the singular.

**Comment by edwardleardi** [comment]
Not sure if it makes sense in the future to consider creating a separate class to represent a dataset schema, e.g. `SchemaDict`. There could be benefits to this such as having a `__repr__` method for `SchemaDict`s instead of using `get_dataset_metadata`.

**Comment by xuhdev** [comment]
Do you mean `DATASET_SCHEMATA` (plurality on schema instead of dataset)?

I think the main source of confusion comes from what ONE schema is. When we wrote that part I think we had "one file, one schema" in mind. I'm pretty sure we have some spots in the doc mixing up the plurality. We don't have to follow this rule, just need some consistency and clarification.

**Comment by edwardleardi** [comment]
I mean `DATASETS_SCHEMA_URL` in place of `DATASET_SCHEMA_URL` and `DatasetsSchema` in place of `DatasetSchema` (and the same for formats and licenses). 

> I think the main source of confusion comes from what ONE schema is.

Yes I agree. The way I interpret it currently is each of `DATASET_SCHEMA_URL`, `FORMAT_SCHEMA_URL`, `LICENSE_SCHEMA_URL` represents a separate single schema containing multiple datasets, formats, licenses (hence why I think those should be plural). However we also formally refer to the dictionary that we feed to `Dataset` during instantiation as a `SchemaDict` and informally as a "dataset schema", which is where it could get confusing. 

If we use `DATASET_SCHEMATA`, then I feel it may get ever more confusing, because the `DATASET_SCHEMATA` would be a schema on its own composed of schemata. So referring to "the schemata" would be unclear if we mean `DATASET_SCHEMATA` or all three schemata `DATASET_SCHEMATA`, `LICENSE_SCHEMATA`, and `FORMAT_SCHEMATA`.

**Comment by xuhdev** [comment]
I see what you mean. We should have a fix that updates the documents and naming in one shot so that we don't end up with inconsistency. We should also have a glossary on various terms ("messaging dos and don'ts")

**Comment by edwardleardi** [comment]
Yeah I agree, the glossary is a good idea too.

**Comment by xuhdev** [comment]
@edwardleardi This is where we were discussing the issue on the naming

**Comment by xuhdev** [comment]
Let's stick with the convention that the part that is passed to `Dataset` is called a **schema**. (In fact, the name of the parameter of `Dataset`'s constructor is called `schema`.) That means, ONE schema represent ONE dataset. Then, a schema file would contain multiple schemata. It's called a "schema file" not a "schemata file" because of the [rule of the plural form of a noun + noun compound](https://www.myenglishpages.com/english/grammar-lesson-plural-compound-nouns.php) (you say "package delivery", not "packages delivery"). Similarly, following this convention, we would call it `DATASET_SCHEMATA` not `DATASETS_SCHEMA`.

I'll write these to the document when I start working on it.

**Comment by xuhdev** [comment]
To make things easier, we'll refer to the content of a schema file as a "schema collection". Therefore:

- A schema file contains a schema collection.
- a schema collection contains multiple schemata.
